"""
Shapeshifters Healthcare — Live Medical News Database
Auto-generated by RSS fetcher on 2026-03-21 17:56
Sources: Times of India Health, NDTV Health, WHO News, MedicalXpress
DO NOT edit manually — this file is overwritten every 6 hours
"""

from datetime import datetime

LIVE_NEWS_DATABASE = [
    {
        "headline": "Restless Legs Syndrome can turn rest into discomfort: what is it, and how is it treated",
        "summary": "An uncomfortable urge to move the legs while resting, often accompanied by crawling or tingling sensations may be a sign of Restless Legs Syndrome, a neurological condition that can significantly disrupt sleep and affect daily functioning",
        "source": "The Hindu Health",
        "country": "India",
        "specialty": [
            "Neurology"
        ],
        "audience": [
            "patients",
            "general"
        ],
        "impact": "Medium",
        "date": "2026-03-21",
        "url": "https://www.thehindu.com/sci-tech/health/restless-legs-syndrome-can-turn-rest-into-discomfort-what-is-it-and-how-is-it-treated/article70731101.ece",
        "type": "news",
        "clinical_relevance": "Latest update from The Hindu Health — Neurology",
        "read_more": "https://www.thehindu.com/sci-tech/health/restless-legs-syndrome-can-turn-rest-into-discomfort-what-is-it-and-how-is-it-treated/article70731101.ece",
        "news_id": "LIVE001"
    },
    {
        "headline": "Sun Pharma, Dr. Reddy’s, Zydus, Glenmark roll out generic Semaglutide",
        "summary": "The generic drugmakers, with many more expected to make announcements, are eyeing a share of the market for Semaglutide in India, which is estimated to be $1 billion over the next couple of years",
        "source": "The Hindu Health",
        "country": "India",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "patients",
            "general"
        ],
        "impact": "Medium",
        "date": "2026-03-21",
        "url": "https://www.thehindu.com/business/sun-pharma-dr-reddys-zydus-glenmark-roll-out-generic-semaglutide/article70768590.ece",
        "type": "news",
        "clinical_relevance": "Latest update from The Hindu Health — General Medicine",
        "read_more": "https://www.thehindu.com/business/sun-pharma-dr-reddys-zydus-glenmark-roll-out-generic-semaglutide/article70768590.ece",
        "news_id": "LIVE002"
    },
    {
        "headline": "The rising tide of eco‑anxiety among India’s youth: a call for climate resilience",
        "summary": "The younger generation, navigating generational divergence, often faces a dual allegiance of morally adhering to familial practices and responding ethically to the global planet crisis. This means that they could be facing more eco-guilt whilst trying to stay aligned with traditional practices",
        "source": "The Hindu Health",
        "country": "India",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "patients",
            "general"
        ],
        "impact": "Medium",
        "date": "2026-03-21",
        "url": "https://www.thehindu.com/sci-tech/health/the-rising-tide-of-eco%E2%80%90anxiety-among-indias-youth-a-call-for-climate-resilience/article70749320.ece",
        "type": "news",
        "clinical_relevance": "Latest update from The Hindu Health — General Medicine",
        "read_more": "https://www.thehindu.com/sci-tech/health/the-rising-tide-of-eco%E2%80%90anxiety-among-indias-youth-a-call-for-climate-resilience/article70749320.ece",
        "news_id": "LIVE003"
    },
    {
        "headline": "Testosterone improves fat distribution for older women",
        "summary": "As we age, the amount and distribution of fat in our bodies changes. Most fat is subcutaneous—meaning it is stored just under the skin. Subcutaneous fat generally does not have detrimental health impacts. In fact, we need some amount of fat to be healthy. Visceral fat, however, is stored in the gut",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "Dermatology"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-21",
        "url": "https://medicalxpress.com/news/2026-03-testosterone-fat-older-women.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — Dermatology",
        "read_more": "https://medicalxpress.com/news/2026-03-testosterone-fat-older-women.html",
        "news_id": "LIVE004"
    },
    {
        "headline": "Discovery might inform new approach to Huntington's disease",
        "summary": "Treatments that target a fragment of the mutant protein that causes Huntington's disease might be more effective than treatments—now in clinical trials—that target the whole protein but leave this fragment intact, a new study in mice suggests. The findings appear in Science Translational Medicine.",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-21",
        "url": "https://medicalxpress.com/news/2026-03-discovery-approach-huntington-disease.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — General Medicine",
        "read_more": "https://medicalxpress.com/news/2026-03-discovery-approach-huntington-disease.html",
        "news_id": "LIVE005"
    },
    {
        "headline": "Novel blood marker may help predict cognitive impairment after a cardiac arrest",
        "summary": "Routine early measurement of the neurofilament light chain could help improve prediction of cognitive impairment after out-of-hospital cardiac arrest, according to a study presented today at ESC Acute CardioVascular Care 2026, the annual congress of the Association for Acute CardioVascular Care (ACV",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "Cardiology"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-21",
        "url": "https://medicalxpress.com/news/2026-03-blood-marker-cognitive-impairment-cardiac.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — Cardiology",
        "read_more": "https://medicalxpress.com/news/2026-03-blood-marker-cognitive-impairment-cardiac.html",
        "news_id": "LIVE006"
    },
    {
        "headline": "A blood test may tailor breast cancer treatment for older women",
        "summary": "For women age 70 and over with a common form of breast cancer, determining \"the right size\" of treatment can be challenging, in part because clinicians have limited tools to guide individualized treatment decisions. In a study published today in Clinical Cancer Research, scientists at UPMC Hillman C",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "Oncology"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-21",
        "url": "https://medicalxpress.com/news/2026-03-blood-tailor-breast-cancer-treatment.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — Oncology",
        "read_more": "https://medicalxpress.com/news/2026-03-blood-tailor-breast-cancer-treatment.html",
        "news_id": "LIVE007"
    },
    {
        "headline": "The epigenetics of trauma: 86 miRNAs linked to PTSD symptom severity and social adversity",
        "summary": "Adverse childhood experiences and traumatic events experienced or witnessed at any point during one's lifetime can sometimes prompt the emergence of some mental health disorders, such as post-traumatic stress disorder (PTSD) and complex PTSD (c-PTSD). Past studies suggest that these disorders emerge",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-21",
        "url": "https://medicalxpress.com/news/2026-03-epigenetics-trauma-mirnas-linked-ptsd.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — General Medicine",
        "read_more": "https://medicalxpress.com/news/2026-03-epigenetics-trauma-mirnas-linked-ptsd.html",
        "news_id": "LIVE008"
    },
    {
        "headline": "How exercise can lower your cancer risk",
        "summary": "Exercise. It can be hard for a lot of us to get started. Regardless of how you feel about physical activity, it comes with various benefits. One benefit of exercise that is not often recognized is its assistance in lowering cancer risk.",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "Oncology"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-21",
        "url": "https://medicalxpress.com/news/2026-03-cancer.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — Oncology",
        "read_more": "https://medicalxpress.com/news/2026-03-cancer.html",
        "news_id": "LIVE009"
    },
    {
        "headline": "Researchers launch OZ-ABCD tool to curb medication harm in aged care",
        "summary": "Researchers at Monash University, together with a multidisciplinary team of health care professionals and medication safety experts, have developed the first national consensus list of medicines with a high risk of harm in Australian residential aged care. Published in the Australasian Journal on Ag",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-21",
        "url": "https://medicalxpress.com/news/2026-03-oz-abcd-tool-curb-medication.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — General Medicine",
        "read_more": "https://medicalxpress.com/news/2026-03-oz-abcd-tool-curb-medication.html",
        "news_id": "LIVE010"
    },
    {
        "headline": "Coping with chronic disease when food is scarce takes its toll on mental health, researchers find",
        "summary": "Twenty-five years into her diabetes and youth research, epidemiology professor Angela Liese and her team continue to increase our understanding of this uniquely vulnerable population. The team's recent findings reveal that youth and young adults who have diabetes and experience food insecurity have",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "Diabetes & Endocrinology"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-21",
        "url": "https://medicalxpress.com/news/2026-03-coping-chronic-disease-food-scarce.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — Diabetes & Endocrinology",
        "read_more": "https://medicalxpress.com/news/2026-03-coping-chronic-disease-food-scarce.html",
        "news_id": "LIVE011"
    },
    {
        "headline": "Study finds FGFR1 boosts cholesterol uptake in prostate cancer cells",
        "summary": "Researchers at Texas A&amp;M Health have identified a molecular mechanism that increases cholesterol levels inside prostate cancer cells—an important process that may help explain how some tumors progress and become resistant to treatment.",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "Oncology"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-21",
        "url": "https://medicalxpress.com/news/2026-03-fgfr1-boosts-cholesterol-uptake-prostate.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — Oncology",
        "read_more": "https://medicalxpress.com/news/2026-03-fgfr1-boosts-cholesterol-uptake-prostate.html",
        "news_id": "LIVE012"
    },
    {
        "headline": "How poor oral health could affect your thinking and memory",
        "summary": "Gum disease together with tooth loss can result in structural changes in the brain that  produce cognitive decline and increase the likelihood of neurodegenerative disorders",
        "source": "The Hindu Health",
        "country": "India",
        "specialty": [
            "Neurology"
        ],
        "audience": [
            "patients",
            "general"
        ],
        "impact": "Medium",
        "date": "2026-03-20",
        "url": "https://www.thehindu.com/sci-tech/health/how-poor-oral-health-could-affect-your-thinking-and-memory/article70738228.ece",
        "type": "news",
        "clinical_relevance": "Latest update from The Hindu Health — Neurology",
        "read_more": "https://www.thehindu.com/sci-tech/health/how-poor-oral-health-could-affect-your-thinking-and-memory/article70738228.ece",
        "news_id": "LIVE013"
    },
    {
        "headline": "Webinar on patient-centric and tech-enabled TB care to be held on March 20",
        "summary": "Webinar on patient-centric and tech-enabled TB care to be held on March 20",
        "source": "The Hindu Health",
        "country": "India",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "patients",
            "general"
        ],
        "impact": "Medium",
        "date": "2026-03-20",
        "url": "https://www.thehindu.com/sci-tech/health/webinar-on-patient-centric-and-tech-enabled-tb-care-to-be-held-on-march-20/article70749472.ece",
        "type": "news",
        "clinical_relevance": "Latest update from The Hindu Health — General Medicine",
        "read_more": "https://www.thehindu.com/sci-tech/health/webinar-on-patient-centric-and-tech-enabled-tb-care-to-be-held-on-march-20/article70749472.ece",
        "news_id": "LIVE014"
    },
    {
        "headline": "Workshop on mental health systems assessment held",
        "summary": "Key stakeholders from various departments and experts from NIMHANS participated in reviewing and validating findings on mental health infrastructure and services",
        "source": "The Hindu Health",
        "country": "India",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "patients",
            "general"
        ],
        "impact": "Medium",
        "date": "2026-03-20",
        "url": "https://www.thehindu.com/sci-tech/health/workshop-on-mental-health-systems-assessment-held/article70764600.ece",
        "type": "news",
        "clinical_relevance": "Latest update from The Hindu Health — General Medicine",
        "read_more": "https://www.thehindu.com/sci-tech/health/workshop-on-mental-health-systems-assessment-held/article70764600.ece",
        "news_id": "LIVE015"
    },
    {
        "headline": "Women and TB in India: a story of deprivation, discrimination and debt",
        "summary": "Women in India face problems from the very beginning of their TB journey: late diagnoses or misdiagnoses are compounded by stigma, limited mobility, lack of finances and multiple barriers to care",
        "source": "The Hindu Health",
        "country": "India",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "patients",
            "general"
        ],
        "impact": "Medium",
        "date": "2026-03-20",
        "url": "https://www.thehindu.com/sci-tech/health/women-and-tb-in-india-a-story-of-deprivation-discrimination-and-debt/article70749548.ece",
        "type": "news",
        "clinical_relevance": "Latest update from The Hindu Health — General Medicine",
        "read_more": "https://www.thehindu.com/sci-tech/health/women-and-tb-in-india-a-story-of-deprivation-discrimination-and-debt/article70749548.ece",
        "news_id": "LIVE016"
    },
    {
        "headline": "Why is ORS not used enough in India, and why it should be",
        "summary": "Diarrhoeal illnesses and heat-related dehydration affect children across India. Doctors emphasise that timely use of Oral Rehydration Solution (ORS) can prevent complications and hospitalisation",
        "source": "The Hindu Health",
        "country": "India",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "patients",
            "general"
        ],
        "impact": "Medium",
        "date": "2026-03-20",
        "url": "https://www.thehindu.com/sci-tech/health/why-is-ors-not-used-enough-in-india-and-why-it-should-be/article70749586.ece",
        "type": "news",
        "clinical_relevance": "Latest update from The Hindu Health — General Medicine",
        "read_more": "https://www.thehindu.com/sci-tech/health/why-is-ors-not-used-enough-in-india-and-why-it-should-be/article70749586.ece",
        "news_id": "LIVE017"
    },
    {
        "headline": "Queensland GPs face barriers in supporting voluntary assisted dying, study finds",
        "summary": "Queensland general practitioners provide compassionate, holistic care to patients seeking voluntary assisted dying (VAD), but many face significant hurdles that limit their capacity to participate, new QUT-led research has found.",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-20",
        "url": "https://medicalxpress.com/news/2026-03-queensland-gps-barriers-voluntary-dying.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — General Medicine",
        "read_more": "https://medicalxpress.com/news/2026-03-queensland-gps-barriers-voluntary-dying.html",
        "news_id": "LIVE018"
    },
    {
        "headline": "What is Flumist, the new flu vaccine for kids that's sprayed in their noses?",
        "summary": "Many kids are scared of getting needles, and this can stop them getting vaccinations that protect that against the flu. Less than 1 in 4 Australian children were vaccinated against influenza in 2025.",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "General Medicine"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-20",
        "url": "https://medicalxpress.com/news/2026-03-flumist-flu-vaccine-kids-sprayed.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — General Medicine",
        "read_more": "https://medicalxpress.com/news/2026-03-flumist-flu-vaccine-kids-sprayed.html",
        "news_id": "LIVE019"
    },
    {
        "headline": "I'm a kidney surgeon: Here's why I hope I never see you",
        "summary": "As a urological surgeon, I meet many patients with chronic (long-term) kidney disease. Sometimes, I see patients that have progressed to the point where their kidneys do not work at all. This leads to the toxic build-up of waste products, meaning they need regular dialysis or a kidney transplant.",
        "source": "MedicalXpress",
        "country": "International",
        "specialty": [
            "Surgery"
        ],
        "audience": [
            "clinicians",
            "researchers"
        ],
        "impact": "High",
        "date": "2026-03-20",
        "url": "https://medicalxpress.com/news/2026-03-im-kidney-surgeon.html",
        "type": "news",
        "clinical_relevance": "Latest update from MedicalXpress — Surgery",
        "read_more": "https://medicalxpress.com/news/2026-03-im-kidney-surgeon.html",
        "news_id": "LIVE020"
    }
]

LAST_UPDATED = "2026-03-21 17:56:08"
TOTAL_ARTICLES = 20
SOURCES = ["Times of India Health", "NDTV Health", "WHO News", "MedicalXpress"]


async def get_live_news(args: dict) -> dict:
    specialty = args.get("specialty", "").lower()
    impact    = args.get("impact", "").lower()
    limit     = int(args.get("limit", 5))
    country   = args.get("country", "").lower()

    results = LIVE_NEWS_DATABASE

    if specialty:
        results = [n for n in results if any(specialty in s.lower() for s in n.get("specialty", []))]
    if impact:
        results = [n for n in results if n.get("impact", "").lower() == impact]
    if country:
        results = [n for n in results if country in n.get("country", "").lower()]

    results = results[:limit]

    if not results:
        return {
            "status": "no_results",
            "message": "No live news matched your filters.",
            "last_updated": LAST_UPDATED,
        }

    return {
        "status": "success",
        "count": len(results),
        "last_updated": LAST_UPDATED,
        "sources": SOURCES,
        "news": results,
    }


async def get_news_by_country(args: dict) -> dict:
    country = args.get("country", "india").lower()
    results = [n for n in LIVE_NEWS_DATABASE if country in n.get("country", "").lower()]
    return {
        "status": "success",
        "country": country,
        "count": len(results),
        "news": results[:5],
        "last_updated": LAST_UPDATED,
    }


async def get_news_summary_live(args: dict) -> dict:
    indian_news = [n for n in LIVE_NEWS_DATABASE if n.get("country") == "India"]
    intl_news   = [n for n in LIVE_NEWS_DATABASE if n.get("country") == "International"]
    high_impact = [n for n in LIVE_NEWS_DATABASE if n.get("impact") == "High"]

    return {
        "status": "success",
        "summary": {
            "total_articles":    len(LIVE_NEWS_DATABASE),
            "indian_news":       len(indian_news),
            "international":     len(intl_news),
            "high_impact":       len(high_impact),
            "last_updated":      LAST_UPDATED,
            "sources":           SOURCES,
        },
        "top_headlines": [
            {
                "headline": n["headline"],
                "source":   n["source"],
                "impact":   n["impact"],
                "url":      n["url"],
            }
            for n in LIVE_NEWS_DATABASE[:3]
        ],
    }
