"""
Shapeshifters Healthcare — SEO Content Strategy
32 articles mapped to affiliate placements, AdSense slots, and content outlines.

Article Types:
  N = National SEO (broad India-wide keyword)
  L = Local SEO  (city + specialty keyword)
  F = Featured / high-RPM hybrid

Priority order for writing (highest RPM first):
  N006, F001, L011, L004, N005, N004, N003, L001, L002, L003, ...
"""

ARTICLES = [
    # ──────────────────────────────────────────────────────────────
    # NATIONAL SEO ARTICLES
    # ──────────────────────────────────────────────────────────────
    {
        "id": "N001",
        "slug": "metformin-side-effects-india",
        "title": "Metformin Side Effects: What Every Indian Diabetic Patient Must Know",
        "specialty": "diabetes",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "metformin side effects",
        "secondary_keywords": ["metformin dosage India", "metformin lactic acidosis", "metformin and kidney"],
        "estimated_monthly_searches": 8100,
        "rpm_estimate": 4.5,
        "affiliate_placement": [
            {"partner": "1mg", "placement": "after_dosage_section", "copy": "Order Metformin online — verified pharmacy, home delivery"},
            {"partner": "thyrocare", "placement": "after_monitoring_section", "copy": "HbA1c test at home — ₹249, results in 24 hours"},
        ],
        "article_outline": [
            "H1: Metformin Side Effects: What Every Indian Diabetic Patient Must Know",
            "H2: What Is Metformin and Why Is It Prescribed?",
            "H2: Common Side Effects of Metformin",
            "H3: Gastrointestinal Side Effects",
            "H3: Vitamin B12 Deficiency",
            "H2: Serious but Rare Side Effects",
            "H3: Lactic Acidosis — Warning Signs",
            "H2: Metformin and Kidney Function",
            "H2: How to Minimise Side Effects",
            "H2: When to Call Your Doctor",
            "H2: FAQ",
        ],
    },
    {
        "id": "N002",
        "slug": "diabetes-diet-plan-india",
        "title": "Diabetes Diet Plan for Indians: What to Eat and Avoid",
        "specialty": "diabetes",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "diabetes diet plan India",
        "secondary_keywords": ["diabetic food chart India", "what to eat in diabetes", "Indian food for diabetics"],
        "estimated_monthly_searches": 14800,
        "rpm_estimate": 3.8,
        "affiliate_placement": [
            {"partner": "thyrocare", "placement": "after_intro", "copy": "Check your blood sugar at home — Thyrocare HbA1c kit ₹249"},
            {"partner": "morepen", "placement": "after_monitoring_section", "copy": "Dr. Morepen Glucometer — accurate, affordable, trusted by 1M+ Indians"},
        ],
        "article_outline": [
            "H1: Diabetes Diet Plan for Indians: What to Eat and Avoid",
            "H2: Understanding the Glycaemic Index for Indian Foods",
            "H2: Best Foods for Diabetics in India",
            "H3: Grains and Cereals",
            "H3: Vegetables",
            "H3: Fruits to Include and Avoid",
            "H2: Sample 7-Day Indian Diabetic Meal Plan",
            "H2: Foods to Strictly Avoid",
            "H2: Reading Food Labels in India",
            "H2: FAQ",
        ],
    },
    {
        "id": "N003",
        "slug": "cancer-screening-india",
        "title": "Cancer Screening in India: Complete Guide by Age and Risk",
        "specialty": "oncology",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "cancer screening India",
        "secondary_keywords": ["breast cancer screening", "cervical cancer screening India", "cancer early detection"],
        "estimated_monthly_searches": 6600,
        "rpm_estimate": 6.2,
        "affiliate_placement": [
            {"partner": "thyrocare", "placement": "after_screening_types", "copy": "Book Cancer Screening Panel — Thyrocare, home collection, ₹1499"},
            {"partner": "niva_bupa", "placement": "after_cost_section", "copy": "Critical Illness Cover — Niva Bupa, covers 20+ cancers"},
        ],
        "article_outline": [
            "H1: Cancer Screening in India: Complete Guide by Age and Risk",
            "H2: Why Early Detection Saves Lives",
            "H2: Recommended Screenings by Cancer Type",
            "H3: Breast Cancer",
            "H3: Cervical Cancer",
            "H3: Colorectal Cancer",
            "H3: Oral Cancer",
            "H3: Prostate Cancer",
            "H2: When to Start Screening by Age",
            "H2: Cost of Cancer Screening in India",
            "H2: Government Programmes for Free Screening",
            "H2: FAQ",
        ],
    },
    {
        "id": "N004",
        "slug": "laparoscopic-surgery-recovery",
        "title": "Laparoscopic Surgery Recovery: Day-by-Day Guide for Indian Patients",
        "specialty": "surgery",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "laparoscopic surgery recovery",
        "secondary_keywords": ["recovery after laparoscopy", "laparoscopic surgery diet", "when to resume work after laparoscopy"],
        "estimated_monthly_searches": 5400,
        "rpm_estimate": 5.5,
        "affiliate_placement": [
            {"partner": "niva_bupa", "placement": "after_intro", "copy": "Cashless hospitalisation — Niva Bupa health insurance covers surgery"},
            {"partner": "1mg", "placement": "after_medication_section", "copy": "Get post-surgery medications delivered home — 1mg"},
        ],
        "article_outline": [
            "H1: Laparoscopic Surgery Recovery: Day-by-Day Guide for Indian Patients",
            "H2: What Happens Immediately After Laparoscopic Surgery",
            "H2: Day 1–3: The First 72 Hours",
            "H2: Day 4–7: Going Home",
            "H2: Week 2–4: Gradual Return to Activity",
            "H2: Diet After Laparoscopic Surgery",
            "H2: Signs of Complications to Watch For",
            "H2: When Can You Return to Work?",
            "H2: FAQ",
        ],
    },
    {
        "id": "N005",
        "slug": "dermatologist-acne-treatment-india",
        "title": "Dermatologist-Approved Acne Treatment in India: Costs, Creams & Procedures",
        "specialty": "dermatology",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "acne treatment India dermatologist",
        "secondary_keywords": ["best acne cream India", "dermatologist for acne cost", "tretinoin India"],
        "estimated_monthly_searches": 12100,
        "rpm_estimate": 5.0,
        "affiliate_placement": [
            {"partner": "minimalist", "placement": "after_otc_section", "copy": "Minimalist Niacinamide 10% — dermatologist-recommended, ₹599"},
            {"partner": "1mg", "placement": "after_prescription_section", "copy": "Get prescription skincare delivered — 1mg verified pharmacy"},
        ],
        "article_outline": [
            "H1: Dermatologist-Approved Acne Treatment in India",
            "H2: Types of Acne and Their Severity",
            "H2: OTC Products That Actually Work",
            "H3: Niacinamide",
            "H3: Salicylic Acid",
            "H3: Benzoyl Peroxide",
            "H2: Prescription Treatments in India",
            "H3: Tretinoin (Retin-A)",
            "H3: Clindamycin Gel",
            "H2: In-Clinic Procedures and Their Costs",
            "H2: Skincare Routine for Acne-Prone Skin",
            "H2: FAQ",
        ],
    },
    {
        "id": "N006",
        "slug": "health-insurance-india-guide",
        "title": "Best Health Insurance in India 2025: Complete Buyer's Guide",
        "specialty": "general",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "best health insurance India 2025",
        "secondary_keywords": ["health insurance comparison India", "family floater plan India", "mediclaim policy"],
        "estimated_monthly_searches": 27100,
        "rpm_estimate": 12.0,
        "affiliate_placement": [
            {"partner": "niva_bupa", "placement": "after_intro", "copy": "Niva Bupa — ₹5L cover from ₹318/month, instant policy issuance"},
            {"partner": "star_health", "placement": "after_comparison_table", "copy": "Star Health Comprehensive — best for senior citizens, no sub-limits"},
        ],
        "article_outline": [
            "H1: Best Health Insurance in India 2025: Complete Buyer's Guide",
            "H2: Why Health Insurance is Non-Negotiable in India",
            "H2: Types of Health Insurance Plans",
            "H3: Individual Plans",
            "H3: Family Floater Plans",
            "H3: Critical Illness Plans",
            "H2: Top 5 Health Insurance Companies in India",
            "H2: How to Compare Plans: 10 Key Parameters",
            "H2: How to Claim Health Insurance in India",
            "H2: Tax Benefits Under Section 80D",
            "H2: FAQ",
        ],
    },
    # ──────────────────────────────────────────────────────────────
    # FEATURED HIGH-RPM ARTICLES
    # ──────────────────────────────────────────────────────────────
    {
        "id": "F001",
        "slug": "second-opinion-cancer-diagnosis-india",
        "title": "Getting a Second Opinion on Cancer in India: Why It Matters and How",
        "specialty": "oncology",
        "audience": "patient",
        "type": "featured",
        "primary_keyword": "second opinion cancer India",
        "secondary_keywords": ["cancer second opinion online", "cancer specialist India", "oncologist second opinion"],
        "estimated_monthly_searches": 2900,
        "rpm_estimate": 9.5,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Get a Second Opinion from a senior oncologist — Shapeshifters Consult"},
            {"partner": "niva_bupa", "placement": "after_cost_section", "copy": "Cover your cancer treatment — Niva Bupa Critical Illness Plan"},
        ],
        "article_outline": [
            "H1: Getting a Second Opinion on Cancer in India: Why It Matters and How",
            "H2: Why Oncology Second Opinions Change Treatment Plans",
            "H2: When to Seek a Second Opinion",
            "H2: How to Request Your Medical Records",
            "H2: Where to Get a Cancer Second Opinion in India",
            "H2: Online vs In-Person Second Opinion",
            "H2: Cost of a Second Opinion in India",
            "H2: FAQ",
        ],
    },
    # ──────────────────────────────────────────────────────────────
    # LOCAL SEO ARTICLES — BANGALORE
    # ──────────────────────────────────────────────────────────────
    {
        "id": "L001",
        "slug": "best-diabetes-specialist-bangalore",
        "title": "Best Diabetes Specialist in Bangalore: Top Endocrinologists 2025",
        "specialty": "diabetes",
        "audience": "patient",
        "type": "local",
        "city": "Bangalore",
        "primary_keyword": "best diabetes specialist Bangalore",
        "secondary_keywords": ["diabetologist Bangalore", "endocrinologist Bangalore", "diabetes doctor Koramangala"],
        "estimated_monthly_searches": 1900,
        "rpm_estimate": 7.0,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Book a diabetes consultation online — verified Bangalore specialist"},
            {"partner": "thyrocare", "placement": "after_tests_section", "copy": "HbA1c + full diabetes panel at home in Bangalore — Thyrocare ₹499"},
        ],
        "article_outline": [
            "H1: Best Diabetes Specialist in Bangalore",
            "H2: How to Choose a Diabetologist in Bangalore",
            "H2: Top Areas for Diabetes Specialists in Bangalore",
            "H3: Koramangala",
            "H3: Indiranagar",
            "H3: Jayanagar",
            "H3: Whitefield",
            "H2: What to Expect at Your First Appointment",
            "H2: Key Tests Your Doctor Will Order",
            "H2: Cost of Diabetes Consultation in Bangalore",
            "H2: FAQ",
        ],
    },
    {
        "id": "L002",
        "slug": "best-oncologist-bangalore",
        "title": "Best Oncologist in Bangalore: Cancer Specialists & Treatment Centres 2025",
        "specialty": "oncology",
        "audience": "patient",
        "type": "local",
        "city": "Bangalore",
        "primary_keyword": "best oncologist Bangalore",
        "secondary_keywords": ["cancer specialist Bangalore", "oncology hospital Bangalore", "chemotherapy Bangalore"],
        "estimated_monthly_searches": 1600,
        "rpm_estimate": 8.5,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Speak to a senior oncologist online before your appointment"},
            {"partner": "niva_bupa", "placement": "after_cost_section", "copy": "Cancer treatment can cost ₹5–20L — protect yourself with Niva Bupa"},
        ],
        "article_outline": [
            "H1: Best Oncologist in Bangalore",
            "H2: Leading Cancer Hospitals in Bangalore",
            "H2: Types of Oncologists You May Need",
            "H3: Medical Oncologist",
            "H3: Surgical Oncologist",
            "H3: Radiation Oncologist",
            "H2: What to Bring to Your First Oncology Appointment",
            "H2: Cost of Cancer Treatment in Bangalore",
            "H2: FAQ",
        ],
    },
    {
        "id": "L003",
        "slug": "best-general-surgeon-bangalore",
        "title": "Best General Surgeon in Bangalore: Laparoscopic & Abdominal Surgery 2025",
        "specialty": "surgery",
        "audience": "patient",
        "type": "local",
        "city": "Bangalore",
        "primary_keyword": "best general surgeon Bangalore",
        "secondary_keywords": ["laparoscopic surgeon Bangalore", "hernia surgery Bangalore", "appendix surgery Bangalore"],
        "estimated_monthly_searches": 1300,
        "rpm_estimate": 7.5,
        "affiliate_placement": [
            {"partner": "niva_bupa", "placement": "after_intro", "copy": "Cashless surgery at 10,000+ hospitals — Niva Bupa health insurance"},
            {"partner": "second_opinion", "placement": "after_procedure_section", "copy": "Get a surgical second opinion online — Shapeshifters Consult"},
        ],
        "article_outline": [
            "H1: Best General Surgeon in Bangalore",
            "H2: Common Surgeries Performed in Bangalore",
            "H2: Laparoscopic vs Open Surgery — Which Is Right for You?",
            "H2: Top Areas for Surgical Clinics in Bangalore",
            "H2: Cost of Common Surgeries in Bangalore",
            "H2: Choosing the Right Hospital for Surgery",
            "H2: FAQ",
        ],
    },
    {
        "id": "L004",
        "slug": "best-dermatologist-bangalore",
        "title": "Best Dermatologist in Bangalore: Skin, Hair & Acne Specialists 2025",
        "specialty": "dermatology",
        "audience": "patient",
        "type": "local",
        "city": "Bangalore",
        "primary_keyword": "best dermatologist Bangalore",
        "secondary_keywords": ["skin specialist Bangalore", "acne treatment Bangalore", "hair loss doctor Bangalore"],
        "estimated_monthly_searches": 3600,
        "rpm_estimate": 6.5,
        "affiliate_placement": [
            {"partner": "minimalist", "placement": "after_skincare_routine", "copy": "Dermatologist-recommended skincare — Minimalist, free shipping Bangalore"},
            {"partner": "1mg", "placement": "after_prescription_section", "copy": "Get prescription skincare delivered in Bangalore — 1mg"},
        ],
        "article_outline": [
            "H1: Best Dermatologist in Bangalore",
            "H2: Skin Conditions Commonly Treated in Bangalore",
            "H2: Top Areas for Dermatology Clinics",
            "H3: HSR Layout",
            "H3: JP Nagar",
            "H3: Malleshwaram",
            "H2: What to Expect at a Dermatology Appointment",
            "H2: Cost of Dermatology Treatment in Bangalore",
            "H2: At-Home Skincare Routine Recommended by Bangalore Dermatologists",
            "H2: FAQ",
        ],
    },
    # ──────────────────────────────────────────────────────────────
    # LOCAL SEO ARTICLES — MUMBAI
    # ──────────────────────────────────────────────────────────────
    {
        "id": "L005",
        "slug": "best-diabetes-specialist-mumbai",
        "title": "Best Diabetes Specialist in Mumbai: Top Endocrinologists 2025",
        "specialty": "diabetes",
        "audience": "patient",
        "type": "local",
        "city": "Mumbai",
        "primary_keyword": "best diabetes specialist Mumbai",
        "secondary_keywords": ["diabetologist Mumbai", "endocrinologist Mumbai", "diabetes doctor Bandra"],
        "estimated_monthly_searches": 2400,
        "rpm_estimate": 7.0,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Book a diabetes consultation online — verified Mumbai specialist"},
            {"partner": "thyrocare", "placement": "after_tests_section", "copy": "HbA1c at home in Mumbai — Thyrocare ₹249"},
        ],
        "article_outline": [
            "H1: Best Diabetes Specialist in Mumbai",
            "H2: How to Choose a Diabetologist in Mumbai",
            "H2: Top Areas for Diabetes Specialists",
            "H3: Bandra",
            "H3: Andheri",
            "H3: Powai",
            "H2: Cost of Diabetes Consultation in Mumbai",
            "H2: FAQ",
        ],
    },
    {
        "id": "L006",
        "slug": "best-oncologist-mumbai",
        "title": "Best Oncologist in Mumbai: Cancer Specialists & Treatment Centres 2025",
        "specialty": "oncology",
        "audience": "patient",
        "type": "local",
        "city": "Mumbai",
        "primary_keyword": "best oncologist Mumbai",
        "secondary_keywords": ["cancer specialist Mumbai", "oncology hospital Mumbai", "Tata Memorial"],
        "estimated_monthly_searches": 2200,
        "rpm_estimate": 8.5,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Get a senior oncologist's second opinion online"},
            {"partner": "niva_bupa", "placement": "after_cost_section", "copy": "Cashless cancer treatment cover — Niva Bupa"},
        ],
        "article_outline": [
            "H1: Best Oncologist in Mumbai",
            "H2: Premier Cancer Hospitals in Mumbai",
            "H2: Tata Memorial Centre — What to Know Before You Go",
            "H2: Types of Cancer Treatment in Mumbai",
            "H2: Cost of Cancer Treatment in Mumbai",
            "H2: FAQ",
        ],
    },
    {
        "id": "L007",
        "slug": "best-dermatologist-mumbai",
        "title": "Best Dermatologist in Mumbai: Skin Specialists for Acne, Pigmentation & Hair 2025",
        "specialty": "dermatology",
        "audience": "patient",
        "type": "local",
        "city": "Mumbai",
        "primary_keyword": "best dermatologist Mumbai",
        "secondary_keywords": ["skin specialist Mumbai", "acne treatment Mumbai", "dermatology clinic Bandra"],
        "estimated_monthly_searches": 4400,
        "rpm_estimate": 6.5,
        "affiliate_placement": [
            {"partner": "minimalist", "placement": "after_skincare_routine", "copy": "Minimalist Skincare — Mumbai delivery, dermatologist-formulated"},
            {"partner": "1mg", "placement": "after_prescription_section", "copy": "Prescription skincare delivered in Mumbai — 1mg verified"},
        ],
        "article_outline": [
            "H1: Best Dermatologist in Mumbai",
            "H2: Top Skin Conditions Treated in Mumbai",
            "H2: Top Areas for Dermatology Clinics in Mumbai",
            "H2: Cost of Dermatology Procedures in Mumbai",
            "H2: FAQ",
        ],
    },
    # ──────────────────────────────────────────────────────────────
    # LOCAL SEO ARTICLES — HYDERABAD
    # ──────────────────────────────────────────────────────────────
    {
        "id": "L008",
        "slug": "best-diabetes-specialist-hyderabad",
        "title": "Best Diabetes Specialist in Hyderabad: Top Endocrinologists 2025",
        "specialty": "diabetes",
        "audience": "patient",
        "type": "local",
        "city": "Hyderabad",
        "primary_keyword": "best diabetes specialist Hyderabad",
        "secondary_keywords": ["diabetologist Hyderabad", "endocrinologist Hyderabad", "KPHB diabetes doctor"],
        "estimated_monthly_searches": 1600,
        "rpm_estimate": 6.5,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Book a diabetes consultation online — verified Hyderabad specialist"},
            {"partner": "thyrocare", "placement": "after_tests_section", "copy": "HbA1c at home in Hyderabad — Thyrocare ₹249"},
        ],
        "article_outline": [
            "H1: Best Diabetes Specialist in Hyderabad",
            "H2: Top Areas for Diabetes Specialists",
            "H3: Banjara Hills",
            "H3: Madhapur / HITEC City",
            "H3: Secunderabad",
            "H2: Cost of Diabetes Consultation in Hyderabad",
            "H2: FAQ",
        ],
    },
    {
        "id": "L009",
        "slug": "best-oncologist-hyderabad",
        "title": "Best Oncologist in Hyderabad: Cancer Specialists 2025",
        "specialty": "oncology",
        "audience": "patient",
        "type": "local",
        "city": "Hyderabad",
        "primary_keyword": "best oncologist Hyderabad",
        "secondary_keywords": ["cancer specialist Hyderabad", "oncology hospital Hyderabad"],
        "estimated_monthly_searches": 1200,
        "rpm_estimate": 8.0,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Get a senior oncologist's second opinion online"},
            {"partner": "niva_bupa", "placement": "after_cost_section", "copy": "Cancer cover — Niva Bupa Critical Illness Plan"},
        ],
        "article_outline": [
            "H1: Best Oncologist in Hyderabad",
            "H2: Top Cancer Hospitals in Hyderabad",
            "H2: Types of Cancer Treatment Available",
            "H2: Cost of Cancer Treatment in Hyderabad",
            "H2: FAQ",
        ],
    },
    # ──────────────────────────────────────────────────────────────
    # LOCAL SEO ARTICLES — CHENNAI
    # ──────────────────────────────────────────────────────────────
    {
        "id": "L010",
        "slug": "best-diabetes-specialist-chennai",
        "title": "Best Diabetes Specialist in Chennai: Diabetologists & Endocrinologists 2025",
        "specialty": "diabetes",
        "audience": "patient",
        "type": "local",
        "city": "Chennai",
        "primary_keyword": "best diabetes specialist Chennai",
        "secondary_keywords": ["diabetologist Chennai", "endocrinologist Chennai"],
        "estimated_monthly_searches": 1800,
        "rpm_estimate": 6.5,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Book a diabetes consultation online — verified Chennai specialist"},
            {"partner": "thyrocare", "placement": "after_tests_section", "copy": "HbA1c at home in Chennai — Thyrocare ₹249"},
        ],
        "article_outline": [
            "H1: Best Diabetes Specialist in Chennai",
            "H2: Top Areas for Diabetes Specialists in Chennai",
            "H3: Anna Nagar",
            "H3: Velachery",
            "H3: T. Nagar",
            "H2: Cost of Diabetes Consultation in Chennai",
            "H2: FAQ",
        ],
    },
    {
        "id": "L011",
        "slug": "best-oncologist-chennai",
        "title": "Best Oncologist in Chennai: Cancer Treatment & Specialist Hospitals 2025",
        "specialty": "oncology",
        "audience": "patient",
        "type": "local",
        "city": "Chennai",
        "primary_keyword": "best oncologist Chennai",
        "secondary_keywords": ["cancer specialist Chennai", "oncology hospital Chennai", "Apollo cancer centre"],
        "estimated_monthly_searches": 2100,
        "rpm_estimate": 8.5,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Get a senior oncologist's second opinion online"},
            {"partner": "niva_bupa", "placement": "after_cost_section", "copy": "Cancer treatment cover — Niva Bupa"},
        ],
        "article_outline": [
            "H1: Best Oncologist in Chennai",
            "H2: Premier Cancer Hospitals in Chennai",
            "H2: Specialists by Cancer Type",
            "H2: Cost of Cancer Treatment in Chennai",
            "H2: FAQ",
        ],
    },
    # ──────────────────────────────────────────────────────────────
    # LOCAL SEO ARTICLES — DELHI
    # ──────────────────────────────────────────────────────────────
    {
        "id": "L012",
        "slug": "best-diabetes-specialist-delhi",
        "title": "Best Diabetes Specialist in Delhi: Diabetologists & Endocrinologists 2025",
        "specialty": "diabetes",
        "audience": "patient",
        "type": "local",
        "city": "Delhi",
        "primary_keyword": "best diabetes specialist Delhi",
        "secondary_keywords": ["diabetologist Delhi", "endocrinologist Delhi NCR", "diabetes doctor South Delhi"],
        "estimated_monthly_searches": 2600,
        "rpm_estimate": 7.0,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Book a diabetes consultation online — verified Delhi specialist"},
            {"partner": "thyrocare", "placement": "after_tests_section", "copy": "HbA1c at home in Delhi — Thyrocare ₹249"},
        ],
        "article_outline": [
            "H1: Best Diabetes Specialist in Delhi",
            "H2: Top Areas for Diabetes Specialists in Delhi",
            "H3: South Delhi",
            "H3: Dwarka",
            "H3: Rohini",
            "H2: Cost of Diabetes Consultation in Delhi",
            "H2: FAQ",
        ],
    },
    {
        "id": "L013",
        "slug": "best-oncologist-delhi",
        "title": "Best Oncologist in Delhi: Cancer Specialists & AIIMS, Apollo 2025",
        "specialty": "oncology",
        "audience": "patient",
        "type": "local",
        "city": "Delhi",
        "primary_keyword": "best oncologist Delhi",
        "secondary_keywords": ["cancer specialist Delhi", "AIIMS oncology", "Apollo Delhi cancer"],
        "estimated_monthly_searches": 2800,
        "rpm_estimate": 8.5,
        "affiliate_placement": [
            {"partner": "second_opinion", "placement": "after_intro", "copy": "Get a senior oncologist's second opinion online"},
            {"partner": "niva_bupa", "placement": "after_cost_section", "copy": "Cashless cancer treatment — Niva Bupa"},
        ],
        "article_outline": [
            "H1: Best Oncologist in Delhi",
            "H2: Premier Cancer Hospitals in Delhi",
            "H3: AIIMS Oncology",
            "H3: Apollo Hospital Sarita Vihar",
            "H3: Rajiv Gandhi Cancer Institute",
            "H2: Cost of Cancer Treatment in Delhi",
            "H2: FAQ",
        ],
    },
    # ──────────────────────────────────────────────────────────────
    # DOCTOR-AUDIENCE ARTICLES
    # ──────────────────────────────────────────────────────────────
    {
        "id": "D001",
        "slug": "diabetes-management-guidelines-india",
        "title": "Diabetes Management Guidelines India 2024: RSSDI Summary for Clinicians",
        "specialty": "diabetes",
        "audience": "doctor",
        "type": "national",
        "primary_keyword": "diabetes management guidelines India",
        "secondary_keywords": ["RSSDI guidelines 2024", "HbA1c targets India", "type 2 diabetes algorithm"],
        "estimated_monthly_searches": 1200,
        "rpm_estimate": 8.0,
        "affiliate_placement": [
            {"partner": "marrow", "placement": "after_intro", "copy": "Marrow Clinical — Diabetes module with 200+ clinical cases"},
            {"partner": "academy", "placement": "after_guidelines_section", "copy": "Shapeshifters Academy — RSSDI guidelines CME course, 2 CME credits"},
        ],
        "article_outline": [
            "H1: Diabetes Management Guidelines India 2024",
            "H2: RSSDI 2024 Key Updates",
            "H2: HbA1c Targets by Patient Profile",
            "H2: Metformin: First-Line Algorithm",
            "H2: When to Add GLP-1 or SGLT-2",
            "H2: Insulin Initiation in Type 2 DM",
            "H2: Complication Screening Schedule",
            "H2: FAQ",
        ],
    },
    {
        "id": "D002",
        "slug": "marrow-neet-pg-review",
        "title": "Marrow for NEET PG 2025: Honest Review by a Resident Doctor",
        "specialty": "general",
        "audience": "doctor",
        "type": "national",
        "primary_keyword": "Marrow NEET PG review",
        "secondary_keywords": ["Marrow app review", "best app for NEET PG", "NEET PG preparation 2025"],
        "estimated_monthly_searches": 4400,
        "rpm_estimate": 5.5,
        "affiliate_placement": [
            {"partner": "marrow", "placement": "after_pros_cons", "copy": "Try Marrow — 3-day free trial, no credit card needed"},
            {"partner": "amazon", "placement": "after_books_section", "copy": "Harrison's Principles of Internal Medicine — Amazon India"},
        ],
        "article_outline": [
            "H1: Marrow for NEET PG 2025: Honest Review",
            "H2: What Is Marrow?",
            "H2: Marrow's Key Features",
            "H3: Video Lectures",
            "H3: Question Bank",
            "H3: Grand Tests",
            "H2: Pros and Cons",
            "H2: Marrow vs Dams vs PrepLadder",
            "H2: Pricing and Subscription Plans",
            "H2: Best Books to Pair with Marrow",
            "H2: FAQ",
        ],
    },
    {
        "id": "D003",
        "slug": "cme-online-india-doctors",
        "title": "Best Online CME Platforms in India for Doctors 2025",
        "specialty": "general",
        "audience": "doctor",
        "type": "national",
        "primary_keyword": "online CME India doctors",
        "secondary_keywords": ["CME credits India", "MCI CME online", "NMC CME requirements"],
        "estimated_monthly_searches": 1800,
        "rpm_estimate": 6.0,
        "affiliate_placement": [
            {"partner": "academy", "placement": "after_intro", "copy": "Shapeshifters Academy — NMC-recognised CME, earn credits online"},
            {"partner": "marrow", "placement": "after_comparison_table", "copy": "Marrow Clinical — subspecialty CME for working doctors"},
        ],
        "article_outline": [
            "H1: Best Online CME Platforms in India for Doctors 2025",
            "H2: NMC CME Requirements — How Many Credits Do You Need?",
            "H2: Top CME Platforms Compared",
            "H2: Free vs Paid CME in India",
            "H2: How to Log and Verify CME Credits",
            "H2: FAQ",
        ],
    },
    # ──────────────────────────────────────────────────────────────
    # DRUG REFERENCE ARTICLES
    # ──────────────────────────────────────────────────────────────
    {
        "id": "DR001",
        "slug": "ozempic-india-semaglutide-guide",
        "title": "Ozempic (Semaglutide) in India 2025: Availability, Cost & How It Works",
        "specialty": "diabetes",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "Ozempic India semaglutide",
        "secondary_keywords": ["semaglutide India price", "Ozempic weight loss India", "GLP-1 India"],
        "estimated_monthly_searches": 5400,
        "rpm_estimate": 7.5,
        "affiliate_placement": [
            {"partner": "1mg", "placement": "after_availability_section", "copy": "Check semaglutide availability — 1mg verified pharmacy"},
            {"partner": "thyrocare", "placement": "after_monitoring_section", "copy": "Monitor your diabetes on Ozempic — HbA1c + kidney panel at home"},
        ],
        "article_outline": [
            "H1: Ozempic (Semaglutide) in India 2025",
            "H2: What Is Semaglutide?",
            "H2: Is Ozempic Available in India?",
            "H2: How Semaglutide Works",
            "H2: Semaglutide for Weight Loss — What Indian Studies Show",
            "H2: Cost of Semaglutide in India",
            "H2: Side Effects to Know",
            "H2: Who Should NOT Take Semaglutide",
            "H2: FAQ",
        ],
    },
    {
        "id": "DR002",
        "slug": "tretinoin-india-guide",
        "title": "Tretinoin in India: Where to Buy, How to Use, Side Effects",
        "specialty": "dermatology",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "tretinoin India",
        "secondary_keywords": ["Retino-A cream India", "tretinoin prescription India", "retinol vs tretinoin"],
        "estimated_monthly_searches": 9900,
        "rpm_estimate": 5.5,
        "affiliate_placement": [
            {"partner": "1mg", "placement": "after_where_to_buy", "copy": "Buy Retino-A (tretinoin) — 1mg verified, prescription required"},
            {"partner": "minimalist", "placement": "after_moisturiser_section", "copy": "Minimalist Granactive Retinoid 2% — starter retinoid, no prescription needed"},
        ],
        "article_outline": [
            "H1: Tretinoin in India: Complete Guide 2025",
            "H2: What Is Tretinoin?",
            "H2: Tretinoin for Acne vs Anti-Ageing",
            "H2: Is Tretinoin Available OTC in India?",
            "H2: How to Use Tretinoin: The Correct Protocol",
            "H2: Side Effects and How to Manage Them",
            "H2: Tretinoin vs Retinol — Which Should You Choose?",
            "H2: FAQ",
        ],
    },
    # ──────────────────────────────────────────────────────────────
    # GENERAL MEDICINE
    # ──────────────────────────────────────────────────────────────
    {
        "id": "GM001",
        "slug": "thyroid-test-india",
        "title": "Thyroid Test in India: TSH, T3, T4 — Cost, Normal Range, and What It Means",
        "specialty": "general",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "thyroid test India",
        "secondary_keywords": ["TSH test cost India", "thyroid function test", "T3 T4 TSH normal range India"],
        "estimated_monthly_searches": 18100,
        "rpm_estimate": 4.5,
        "affiliate_placement": [
            {"partner": "thyrocare", "placement": "after_intro", "copy": "Thyroid Function Test (TSH + T3 + T4) at home — Thyrocare ₹299"},
            {"partner": "1mg", "placement": "after_results_section", "copy": "Book thyroid test online — 1mg, sample collection at home"},
        ],
        "article_outline": [
            "H1: Thyroid Test in India: TSH, T3, T4 Guide",
            "H2: What Does a Thyroid Test Check?",
            "H2: TSH Normal Range in India",
            "H2: T3 and T4: What They Mean",
            "H2: Hypothyroidism vs Hyperthyroidism — Test Results Explained",
            "H2: Cost of Thyroid Tests in India",
            "H2: How to Prepare for a Thyroid Test",
            "H2: FAQ",
        ],
    },
    {
        "id": "GM002",
        "slug": "blood-pressure-management-india",
        "title": "High Blood Pressure in India: Causes, Treatment and Lifestyle Guide",
        "specialty": "general",
        "audience": "patient",
        "type": "national",
        "primary_keyword": "high blood pressure India",
        "secondary_keywords": ["hypertension treatment India", "BP medicine India", "blood pressure diet India"],
        "estimated_monthly_searches": 12100,
        "rpm_estimate": 4.0,
        "affiliate_placement": [
            {"partner": "morepen", "placement": "after_monitoring_section", "copy": "Dr. Morepen BP Monitor — clinically validated, ₹899"},
            {"partner": "1mg", "placement": "after_medication_section", "copy": "Blood pressure medications — 1mg verified pharmacy, home delivery"},
        ],
        "article_outline": [
            "H1: High Blood Pressure in India: Complete Guide",
            "H2: What Is High Blood Pressure?",
            "H2: Why Is Hypertension So Common in India?",
            "H2: Symptoms and Silent Signs",
            "H2: Treatment Options in India",
            "H3: Lifestyle Changes",
            "H3: Medications Commonly Prescribed",
            "H2: DASH Diet for Indian Kitchens",
            "H2: How to Monitor BP at Home",
            "H2: FAQ",
        ],
    },
]

# ──────────────────────────────────────────────────────────────
# Helper: get article by ID or slug
# ──────────────────────────────────────────────────────────────

def get_article(identifier: str) -> dict | None:
    for a in ARTICLES:
        if a["id"] == identifier or a["slug"] == identifier:
            return a
    return None


def get_articles_by_specialty(specialty: str) -> list[dict]:
    return [a for a in ARTICLES if a.get("specialty") == specialty]


def get_articles_by_city(city: str) -> list[dict]:
    return [a for a in ARTICLES if a.get("city") == city]


def get_articles_sorted_by_rpm() -> list[dict]:
    return sorted(ARTICLES, key=lambda a: a.get("rpm_estimate", 0), reverse=True)


# Priority write order (highest RPM first)
PRIORITY_WRITE_ORDER = [a["id"] for a in get_articles_sorted_by_rpm()]
